    # *******************************
    # NEW Vraag_SubSchalen Table: Primary Key = VSID (autogenerated)
    # *******************************
    VSS = NVL.Dummy_Vraag_SubSchaal #Dummy_Vraag.SubSchalen
    Table_Def_VSS = VSS.Get_Table_Def ( 'Vraag_SubSchaal' )
    DB.Create_Table ( Table_Def_VSS, Renew )


      #*************************************
      # SubSchalen waardering per subvraag opbergen
      #*************************************
      # Doorloop alle vragen
      for V in VL.Vraag [1:] :
        for SPSS in V.Vragenlijst.SPSS_FullName :
          SS = V.SubSchalen [ SPSS ]
          if SS.Not_Empty () :
            print '#@#@#@#@', V.Indx, SS.SPSS, SS.Values
            print VraagIDs [ V.Indx ], SubSchaalIDs [ SS.SPSS ]
            RowID = VSS.Do_SQL_Insert ( DB, 'Vraag_SubSchaal' )
            VL_S.Add ( VL_RowID, RowID )
            VL_VS.Add ( VraagIDs [ V.Indx ], SubSchaalIDs [ SS.SPSS ], RowID )
